services:
  backend:
    container_name: backend
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    env_file: ./backend/.env
    command: >
      sh -c " python manage.py migrate &&
          gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend/:/backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 8081:8081
    # volumes:
    #   - react_build:/frontend
  
  nginx:
    image: nginx:stable
    container_name: server
    restart: on-failure
    ports:
      - "80:8081"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      # - react_build:/var/www/frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
      - frontend

# volumes:
#   react_build: